<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="test2" nsURI="http://test2/1.0" nsPrefix="test2">
  <eClassifiers xsi:type="ecore:EClass" name="Vehicles"/>
  <eClassifiers xsi:type="ecore:EClass" name="Train" eSuperTypes="#//Vehicles"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bus" eSuperTypes="#//Vehicles">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="capacity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
